int _putchar(char c);
void print_alphabet(void);
void print_alphabet_*10(void);
int _islower(int c);
int _isalphat(int c);
int print_sign(int n);
int _abs(int);
int print_last_digit(int);
int jack_bauer(void);
int times_table(void);
int add(int, int);
void print_to_98(int n);
void print_times_table(int n);
